-- Alter the notebooks table to store autogenerated or custom summaries and suggested prompts
alter table public.notebooks add column if not exists summary text;
alter table public.notebooks add column if not exists suggested_prompts text[];
